// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: System.Reflection.AssemblyCompanyAttribute("FSharpKernelGen")>]
[<assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")>]
[<assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")>]
[<assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+e58842480b1f6860a27eae145cf1c1729401fcdf")>]
[<assembly: System.Reflection.AssemblyProductAttribute("FSharpKernelGen")>]
[<assembly: System.Reflection.AssemblyTitleAttribute("FSharpKernelGen")>]
[<assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")>]
do()
