// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: System.Reflection.AssemblyCompanyAttribute("FSharpCompiler")>]
[<assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")>]
[<assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")>]
[<assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+404662b430cdc5b13ee346fd6bb7383c6e11cfee")>]
[<assembly: System.Reflection.AssemblyProductAttribute("FSharpCompiler")>]
[<assembly: System.Reflection.AssemblyTitleAttribute("FSharpCompiler")>]
[<assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")>]
do()
